### PR TITLE
upgrade redix dependency to 1.x

### PR DESCRIPTION
**Pull request by fivetanley**
The breaking changes listed in https://github.com/whatyouhide/redix/blob/main/CHANGELOG.md for 0.9, 0.10, 0.11 don't appear to affect HammerBackendRedis. Redix 1.0 is simply 0.11 but with a 1.0 version number indicating the API should be stable for a while.

### CODE REVIEW

**Comment by devin-henslee** [comment]
Is there anything I can do to help get this merged? I'm working on a project with `exq` that has a dependency conflict with `redix`.

**Comment by fivetanley** [comment]
@ShaneKilkelly sorry for the ping; anything I can do to help get this in?

**Comment by ShaneKilkelly** [comment]
Hi there! Sorry for the delay, I'll try to get this merged in the next few days.

**Comment by maartenvanvliet** [comment]
Can confirm that redix 1.x works with HammerBackendRedis

**Comment by andrewhr** [comment]
Sorry, but there is any updates on this?

I have some conflicts related to `new_relic_agent` which depends on newer Redix telemetry.  If there is any work where I can help with I will be glad to do so we can move this forward :)

I appreciate your time, thank you!

**Comment by validere-ben** [comment]
Chiming in with similar issues with `fun_with_flags` requiring ~1.0 would greatly appreciate any updates on this, glad to provide any assistance needed to get this merged

**Comment by chakeresa** [comment]
@ShaneKilkelly we're also having this conflict that's making HammerBackendRedix unusable. Looks like #22 updates redix as well as the other deps, which is nice.

**Comment by epinault** [comment]
done in master and with 6.1.1

**Pull request closed without merging**
